import express from "express" ;
import { getMe, signup , login , logout } from "../controllers/auth.controller.js";
import { protectRoute } from "../middleware/protectRoute.js" ;

const router = express.Router(); //creates a new router object , where we can define routes for our object

router.get("/me" , protectRoute , getMe) ; //this is gonna be a protected route...
router.post("/signup" , signup); //writing the signup function in auth.controller.js instead...
router.post("/login" , login);//writing the login function in auth.controller.js instead...
router.post("/logout" , logout);//writing the logout function in auth.controller.js instead...

export default router ;